public interface Rentable {
    Decimal calculateRentalCost(Integer days);
}

/*

Vehicle car = new Car('Toyota', 'Camry', 50, true);
car.start();
car.showDetails();
System.debug('Car Rental Cost for 2 days: $' + car.calculateRentalCost(2));

Vehicle bike = new Bike('Honda', 'CBR', 30, true);
bike.start();
bike.showDetails();
System.debug('Bike Rental Cost for 2 days: $' + bike.calculateRentalCost(2));


*/